[platformio]
src_dir = mecanum_car_v2.4_aura

[env:uno_mecanum_aura]
platform = atmelavr@5.1.0
board = uno
framework = arduino
monitor_speed = 9600
lib_deps =
    teckel12/NewPing@^1.9.7
    https://github.com/madsci1016/Arduino-PS2X/archive/refs/heads/master.zip
